### ISSUE TITLE
Tmux status bar

### ISSUE THREAD

**Issue by bpinto** [ajh17/dotfiles#3]
Could you share your tmux configuration for status bar? Thanks!

**Comment by ajh17** [comment]
Sure, you can find my entire ~/.tmux.conf here: https://github.com/ajh17/dotfiles/blob/4f212a0a244f5ec81c29ae926838fceeda6e231f/.tmux.conf

I had deleted the file, sorry, but it's still in the history. 

Enjoy!

**Comment by bpinto** [comment]
Thanks! It seems outdated but that's good enough!
